### ISSUE TITLE
only face detection works even when hand selected 

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxVision#2]
I set the gui to load with hand == true but it still only does face detection.

![Screen Shot 2024-04-10 at 4 36 51 PM](https://github.com/roymacdonald/ofxVision/assets/1054816/41df34b4-c295-4250-997d-b7ad001372c3)

**Comment by roymacdonald** [comment]
Correct. I unimplemented that as I am refactoring a bunch of things.will push the updates soon

**Comment by roymacdonald** [comment]
now all the different detectors work. on the ObjectDetection branch

**Comment by stephanschulz** [comment]
the gui works now in example-ObjectDetection.
thanks.
