### ISSUE TITLE
using a custom .mlmodel created with coreML 

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxVision#4]
I followed [this tutorial to create a simple image classifier model](https://developer.apple.com/documentation/createml/creating-an-image-classifier-model). 
I used 2 sets of images, with each set having about 10 images. Not very big.
My training images have a 1596 × 1138 resolution.

I am now trying to use the example-ObjectDetection example and point i to my model file. My camera resolution is not the same as the model training data. 
I get this error message:

![Screenshot 2024-07-18 at 12 54 48 PM](https://github.com/user-attachments/assets/79d0b967-5350-4f79-aebb-693f1bbfba4c)

Could the difference in resolution be the problem?

This is my model file https://www.dropbox.com/scl/fi/ntl5fg0p04simlracmc5l/hand_or_no_hand_1.mlmodel?rlkey=5c0b4xd3mgt6v3486wyc0wb5g&dl=0

**Comment by stephanschulz** [comment]
i think it might be that this model does not return a rect boundingbox but just a label.
the crash is at ' ofxVision::RectDetection det(ofxVisionHelper::toOf(observation.boundingBox),0);'

my model was training on images that have hands and images without hands. the "create ML" preview returns confidence values for each possible label "hand" , "no hand" but no bounding box.

is there a way to not use any requirement for point or rect return?

**Comment by roymacdonald** [comment]
The results are being cast into the particular type that each model is expected to return. So, in this case it would be just to cast it into a the correct type.
